# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"!\n\x0fLookupIDRequest\x12\x0e\n\x06idNode\x18\x01 \x01(\x05\"3\n\x10LookupIDResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x1e\n\x0bJoinRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"D\n\x16UpdateSuccessorRequest\x12\x13\n\x0bnew_succ_ip\x18\x01 \x01(\t\x12\x15\n\rnew_succ_port\x18\x02 \x01(\x05\")\n\x17UpdateSuccessorResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2M\n\nSearchsucc\x12?\n\x08LookupID\x12\x18.service.LookupIDRequest\x1a\x19.service.LookupIDResponse2C\n\x08Joinnode\x12\x37\n\x08JoinNode\x12\x14.service.JoinRequest\x1a\x15.service.JoinResponse2g\n\x0fUpdateSuccessor\x12T\n\x0fUpdateSuccessor\x12\x1f.service.UpdateSuccessorRequest\x1a .service.UpdateSuccessorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPIDREQUEST']._serialized_start=26
  _globals['_LOOKUPIDREQUEST']._serialized_end=59
  _globals['_LOOKUPIDRESPONSE']._serialized_start=61
  _globals['_LOOKUPIDRESPONSE']._serialized_end=112
  _globals['_JOINREQUEST']._serialized_start=114
  _globals['_JOINREQUEST']._serialized_end=144
  _globals['_JOINRESPONSE']._serialized_start=146
  _globals['_JOINRESPONSE']._serialized_end=177
  _globals['_UPDATESUCCESSORREQUEST']._serialized_start=179
  _globals['_UPDATESUCCESSORREQUEST']._serialized_end=247
  _globals['_UPDATESUCCESSORRESPONSE']._serialized_start=249
  _globals['_UPDATESUCCESSORRESPONSE']._serialized_end=290
  _globals['_SEARCHSUCC']._serialized_start=292
  _globals['_SEARCHSUCC']._serialized_end=369
  _globals['_JOINNODE']._serialized_start=371
  _globals['_JOINNODE']._serialized_end=438
  _globals['_UPDATESUCCESSOR']._serialized_start=440
  _globals['_UPDATESUCCESSOR']._serialized_end=543
# @@protoc_insertion_point(module_scope)
